"""Local storage upload/download routes.

These handle the presigned URLs generated by LocalStorage.presign_upload()
and presign_download(). Without these routes, local file uploads fail
because the signed URL points to a path that doesn't exist.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Query, Request, Response, status

from app.core.config import settings
from app.core.errors import ValidationError
from app.core.media_validation import UnsupportedMediaError, sniff_mime
from app.core.storage import get_storage, verify_local_token

router = APIRouter(prefix="/api/storage", tags=["storage"])


@router.put("/upload/{bucket}/{key:path}", status_code=status.HTTP_204_NO_CONTENT)
async def local_storage_upload(
    request: Request,
    bucket: str,
    key: str,
    expires: Annotated[int, Query()] = 300,
    token: Annotated[str, Query()] = "",
) -> Response:
    """Accept a PUT of raw bytes to local storage using a signed URL.

    This is the target of the signed upload URL produced by
    LocalStorage.presign_upload(). The token is verified before any bytes
    are written.
    """
    if not verify_local_token(bucket, key, "put", expires, token):
        raise ValidationError("Invalid or expired upload token.")

    data = await request.body()
    if len(data) == 0:
        raise ValidationError("The file looks empty.")
    if len(data) > settings.max_upload_bytes:
        raise ValidationError(
            "That file is larger than the upload limit.",
            details={"max_bytes": settings.max_upload_bytes},
        )

    # Validate magic bytes — content-type header is advisory only.
    content_type = request.headers.get("content-type")
    try:
        verified = sniff_mime(data, declared_mime=content_type)
    except UnsupportedMediaError as exc:
        raise ValidationError(str(exc)) from exc

    get_storage().write(bucket, key, data)
    return Response(
        status_code=status.HTTP_204_NO_CONTENT,
        headers={"x-verified-mime": verified},
    )


@router.get("/object/{bucket}/{key:path}")
async def local_storage_download(
    bucket: str,
    key: str,
    expires: Annotated[int, Query()] = 3600,
    token: Annotated[str, Query()] = "",
) -> Response:
    """Serve a stored file using a signed download URL.

    This is the target of the signed download URL produced by
    LocalStorage.presign_download().
    """
    if not verify_local_token(bucket, key, "get", expires, token):
        raise ValidationError("Invalid or expired download token.")

    storage = get_storage()
    local = storage.local_path(bucket, key)
    if local is None or not local.is_file():
        raise ValidationError("File not found in storage.")

    data = local.read_bytes()
    # Guess content type from extension
    suffix = local.suffix.lower()
    mime_map = {
        ".mp4": "video/mp4",
        ".mov": "video/quicktime",
        ".webm": "video/webm",
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".m4a": "audio/mp4",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp",
        ".txt": "text/plain",
        ".pdf": "application/pdf",
    }
    content_type = mime_map.get(suffix, "application/octet-stream")
    return Response(content=data, media_type=content_type)
