"""initial schema

Revision ID: 40b1fee77c73
Revises:
Created: 2026-10-04 07:10:39.683219
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are rendered by autogenerate as `app.core.types.XType()`,
# but Alembic does not emit an import for them. Keeping the import in the
# template means every revision can reference them without a manual fix-up.
import app.core.types

revision: str = "40b1fee77c73"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change. Additive first (AGENTS.md rule 21): never drop a column."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_skills",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "real",
                "mocked",
                "stubbed",
                "future",
                name="impl_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("spec", app.core.types.JSONBType(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_opportunities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "short_form",
                "educational_clip",
                "social_post",
                "carousel",
                "new_idea",
                "gap",
                name="opportunity_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("source_asset_ids", app.core.types.JSONBType(), nullable=False),
        sa.Column("source_ranges", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "effort",
            sa.Enum(
                "low",
                "medium",
                "high",
                name="effort_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "accepted",
                "dismissed",
                name="opportunity_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("origin", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_opportunities", schema=None) as batch_op:
        batch_op.create_index(
            "ix_opportunities_owner_status", ["owner_id", "status"], unique=False
        )

    op.create_table(
        "creator_dna",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("profile", app.core.types.JSONBType(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creator_dna", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_dna_owner_version", ["owner_id", "version"], unique=False
        )

    op.create_table(
        "impact_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("trigger_node_id", sa.Uuid(), nullable=False),
        sa.Column("change", app.core.types.JSONBType(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("impact_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_impact_events_trigger_node_id"),
            ["trigger_node_id"],
            unique=False,
        )

    op.create_table(
        "jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "asset.process",
                "video.analyze",
                "clips.generate",
                "edit.render",
                "archaeology.scan",
                "genome.propagate",
                "dna.learn",
                "reference.analyze",
                name="job_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "cancelled",
                name="job_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("stage", sa.String(length=64), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", app.core.types.JSONBType(), nullable=False),
        sa.Column("result", app.core.types.JSONBType(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_jobs_input_hash", ["input_hash"], unique=False)
        batch_op.create_index(
            "ix_jobs_owner_status", ["owner_id", "status"], unique=False
        )

    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "planning",
                "producing",
                "editing",
                "published",
                "archived",
                name="project_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("intent_id", sa.Uuid(), nullable=True),
        sa.Column("blueprint_id", sa.Uuid(), nullable=True),
        sa.Column("workflow_id", sa.Uuid(), nullable=True),
        sa.Column("cover_asset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(
            "ix_projects_owner_status", ["owner_id", "status"], unique=False
        )

    op.create_table(
        "skill_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("step_id", sa.Uuid(), nullable=True),
        sa.Column("skill_id", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("output", app.core.types.JSONBType(), nullable=False),
        sa.Column("cached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skill_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_skill_runs_project_created", ["project_id", "created_at"], unique=False
        )

    op.create_table(
        "assets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "video",
                "image",
                "audio",
                "script",
                "reference",
                "creator",
                "brand",
                name="asset_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=512), nullable=False),
        sa.Column("mime", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "ready",
                "rejected",
                "failed",
                name="asset_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("tags", app.core.types.JSONBType(), nullable=False),
        sa.Column("meta", app.core.types.JSONBType(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_assets_owner_kind_status", ["owner_id", "kind", "status"], unique=False
        )

    op.create_table(
        "content_nodes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "idea",
                "script",
                "hook",
                "claim",
                "topic",
                "footage",
                "scene",
                "broll",
                "audio",
                "asset",
                "clip",
                "edit",
                "variant",
                "published",
                name="node_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ref_table", sa.String(length=48), nullable=True),
        sa.Column("ref_id", sa.Uuid(), nullable=True),
        sa.Column("label", sa.String(length=300), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "current",
                "stale",
                "archived",
                name="node_state",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("meta", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("content_nodes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_content_nodes_owner_project", ["owner_id", "project_id"], unique=False
        )
        batch_op.create_index(
            "ix_content_nodes_ref", ["ref_table", "ref_id"], unique=False
        )

    op.create_table(
        "creation_blueprints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("intent_id", sa.Uuid(), nullable=True),
        sa.Column("template_key", sa.String(length=64), nullable=False),
        sa.Column("stages", app.core.types.JSONBType(), nullable=False),
        sa.Column("expected_output", app.core.types.JSONBType(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creation_blueprints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creation_blueprints_project_id"),
            ["project_id"],
            unique=False,
        )

    op.create_table(
        "creation_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("primary_text", sa.String(length=500), nullable=False),
        sa.Column("details_text", sa.Text(), nullable=True),
        sa.Column("parsed", app.core.types.JSONBType(), nullable=False),
        sa.Column("confidence", app.core.types.JSONBType(), nullable=False),
        sa.Column("user_edited", sa.Boolean(), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("fallback", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hooks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("script_id", sa.Uuid(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("style", sa.String(length=40), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("hooks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hooks_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "platform_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("parent_node_id", sa.Uuid(), nullable=True),
        sa.Column(
            "platform",
            sa.Enum(
                "instagram_reels",
                "youtube_shorts",
                "tiktok",
                "youtube",
                "linkedin",
                "other",
                name="platform",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("aspect", sa.String(length=16), nullable=False),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("hashtags", app.core.types.JSONBType(), nullable=False),
        sa.Column("adaptation_notes", sa.Text(), nullable=True),
        sa.Column("render_asset_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "impl_status",
            sa.Enum(
                "real",
                "mocked",
                "stubbed",
                "future",
                name="impl_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("platform_variants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_variants_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "scripts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("current_version_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scripts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scripts_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "shot_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("total_duration_s", sa.Float(), nullable=False),
        sa.Column("shots", app.core.types.JSONBType(), nullable=False),
        sa.Column("checklist", app.core.types.JSONBType(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("shot_plans", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_shot_plans_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "analytics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("metric_date", sa.String(length=10), nullable=False),
        sa.Column("metrics", app.core.types.JSONBType(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["platform_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "variant_id", "metric_date", name="uq_analytics_variant_date"
        ),
    )
    op.create_table(
        "asset_embeddings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("ref_start_s", sa.Float(), nullable=True),
        sa.Column("ref_end_s", sa.Float(), nullable=True),
        sa.Column("embedding", app.core.types.VectorType(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("asset_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_asset_embeddings_asset_scope", ["asset_id", "scope"], unique=False
        )

    op.create_table(
        "clips",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("source_asset_id", sa.Uuid(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "target_platform",
            sa.Enum(
                "instagram_reels",
                "youtube_shorts",
                "tiktok",
                "youtube",
                "linkedin",
                "other",
                name="platform",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "accepted",
                "rejected",
                name="clip_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("score_breakdown", app.core.types.JSONBType(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clips", schema=None) as batch_op:
        batch_op.create_index(
            "ix_clips_project_status", ["project_id", "status"], unique=False
        )

    op.create_table(
        "content_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("from_node", sa.Uuid(), nullable=False),
        sa.Column("to_node", sa.Uuid(), nullable=False),
        sa.Column(
            "relation",
            sa.Enum(
                "derived_from",
                "contains",
                "uses",
                "adapts",
                "quotes",
                "matches",
                name="edge_relation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("strength", sa.Float(), nullable=False),
        sa.Column("meta", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["from_node"], ["content_nodes.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["to_node"], ["content_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_node", "to_node", "relation", name="uq_edge_triple"),
    )
    with op.batch_alter_table("content_edges", schema=None) as batch_op:
        batch_op.create_index("ix_content_edges_from", ["from_node"], unique=False)
        batch_op.create_index("ix_content_edges_to", ["to_node"], unique=False)

    op.create_table(
        "impact_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("impact_event_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "affected",
                "text_affected",
                "possibly_affected",
                name="impact_level",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("suggested_change", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "resolution",
            sa.Enum(
                "pending",
                "updated",
                "ignored",
                "reviewed",
                name="resolution",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["impact_event_id"], ["impact_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["node_id"], ["content_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("impact_items", schema=None) as batch_op:
        batch_op.create_index(
            "ix_impact_items_event", ["impact_event_id"], unique=False
        )

    op.create_table(
        "publishing_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("external_url", sa.String(length=512), nullable=True),
        sa.Column(
            "impl_status",
            sa.Enum(
                "real",
                "mocked",
                "stubbed",
                "future",
                name="impl_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("export_package", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["platform_variants.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "references",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("asset_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("creator_attribution", sa.String(length=200), nullable=True),
        sa.Column("license_note", sa.Text(), nullable=True),
        sa.Column("rights_attested", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_references_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("keyframe_path", sa.String(length=512), nullable=True),
        sa.Column("caption", sa.Text(), nullable=False),
        sa.Column("tags", app.core.types.JSONBType(), nullable=False),
        sa.Column("quality", app.core.types.JSONBType(), nullable=False),
        sa.Column("embedding", app.core.types.VectorType(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.create_index("ix_scenes_asset_idx", ["asset_id", "idx"], unique=False)

    op.create_table(
        "script_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("script_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lines", app.core.types.JSONBType(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["script_id"], ["scripts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("script_id", "version", name="uq_script_version"),
    )
    with op.batch_alter_table("script_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_script_versions_script_id"), ["script_id"], unique=False
        )

    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("speaker", sa.String(length=64), nullable=True),
        sa.Column("embedding", app.core.types.VectorType(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_transcript_segments_asset_idx", ["asset_id", "idx"], unique=False
        )

    op.create_table(
        "video_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("stages", app.core.types.JSONBType(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("transcript_json", app.core.types.JSONBType(), nullable=False),
        sa.Column("meta", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id"),
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("blueprint_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_step_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["blueprint_id"], ["creation_blueprints.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_workflows_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "edits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("clip_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("edl", app.core.types.JSONBType(), nullable=False),
        sa.Column("suggestions", app.core.types.JSONBType(), nullable=False),
        sa.Column("render_asset_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["clip_id"], ["clips.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clip_id", "version", name="uq_edit_version"),
    )
    with op.batch_alter_table("edits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_edits_project_id"), ["project_id"], unique=False
        )

    op.create_table(
        "reference_dna",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=False),
        sa.Column("dna", app.core.types.JSONBType(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["reference_id"], ["references.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference_id"),
    )
    op.create_table(
        "script_footage_matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column("line_id", sa.String(length=64), nullable=False),
        sa.Column("asset_id", sa.Uuid(), nullable=False),
        sa.Column("start_s", sa.Float(), nullable=False),
        sa.Column("end_s", sa.Float(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "semantic",
                "visual",
                "beat",
                "manual",
                name="match_method",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["script_version_id"], ["script_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("script_footage_matches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_matches_version_line", ["script_version_id", "line_id"], unique=False
        )

    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.Text(), nullable=True),
        sa.Column("skill_ids", app.core.types.JSONBType(), nullable=False),
        sa.Column("needs", app.core.types.JSONBType(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "locked",
                "ready",
                "running",
                "needs_review",
                "done",
                "failed",
                "skipped",
                name="step_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("input", app.core.types.JSONBType(), nullable=False),
        sa.Column("output_ref", app.core.types.JSONBType(), nullable=False),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("manual", sa.Boolean(), nullable=False),
        sa.Column(
            "impl_status",
            sa.Enum(
                "real",
                "mocked",
                "stubbed",
                "future",
                name="impl_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workflow_steps_workflow_position",
            ["workflow_id", "position"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the change, or state plainly why it cannot be undone."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflow_steps", schema=None) as batch_op:
        batch_op.drop_index("ix_workflow_steps_workflow_position")

    op.drop_table("workflow_steps")
    with op.batch_alter_table("script_footage_matches", schema=None) as batch_op:
        batch_op.drop_index("ix_matches_version_line")

    op.drop_table("script_footage_matches")
    op.drop_table("reference_dna")
    with op.batch_alter_table("edits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_edits_project_id"))

    op.drop_table("edits")
    with op.batch_alter_table("workflows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workflows_project_id"))

    op.drop_table("workflows")
    op.drop_table("video_analyses")
    with op.batch_alter_table("transcript_segments", schema=None) as batch_op:
        batch_op.drop_index("ix_transcript_segments_asset_idx")

    op.drop_table("transcript_segments")
    with op.batch_alter_table("script_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_script_versions_script_id"))

    op.drop_table("script_versions")
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_index("ix_scenes_asset_idx")

    op.drop_table("scenes")
    with op.batch_alter_table("references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_references_project_id"))

    op.drop_table("references")
    op.drop_table("publishing_jobs")
    with op.batch_alter_table("impact_items", schema=None) as batch_op:
        batch_op.drop_index("ix_impact_items_event")

    op.drop_table("impact_items")
    with op.batch_alter_table("content_edges", schema=None) as batch_op:
        batch_op.drop_index("ix_content_edges_to")
        batch_op.drop_index("ix_content_edges_from")

    op.drop_table("content_edges")
    with op.batch_alter_table("clips", schema=None) as batch_op:
        batch_op.drop_index("ix_clips_project_status")

    op.drop_table("clips")
    with op.batch_alter_table("asset_embeddings", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_embeddings_asset_scope")

    op.drop_table("asset_embeddings")
    op.drop_table("analytics")
    with op.batch_alter_table("shot_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shot_plans_project_id"))

    op.drop_table("shot_plans")
    with op.batch_alter_table("scripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scripts_project_id"))

    op.drop_table("scripts")
    with op.batch_alter_table("platform_variants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_variants_project_id"))

    op.drop_table("platform_variants")
    with op.batch_alter_table("hooks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hooks_project_id"))

    op.drop_table("hooks")
    op.drop_table("creation_intents")
    with op.batch_alter_table("creation_blueprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creation_blueprints_project_id"))

    op.drop_table("creation_blueprints")
    with op.batch_alter_table("content_nodes", schema=None) as batch_op:
        batch_op.drop_index("ix_content_nodes_ref")
        batch_op.drop_index("ix_content_nodes_owner_project")

    op.drop_table("content_nodes")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ix_assets_owner_kind_status")

    op.drop_table("assets")
    with op.batch_alter_table("skill_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_skill_runs_project_created")

    op.drop_table("skill_runs")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index("ix_projects_owner_status")

    op.drop_table("projects")
    op.drop_table("profiles")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_owner_status")
        batch_op.drop_index("ix_jobs_input_hash")

    op.drop_table("jobs")
    with op.batch_alter_table("impact_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_impact_events_trigger_node_id"))

    op.drop_table("impact_events")
    with op.batch_alter_table("creator_dna", schema=None) as batch_op:
        batch_op.drop_index("ix_creator_dna_owner_version")

    op.drop_table("creator_dna")
    with op.batch_alter_table("content_opportunities", schema=None) as batch_op:
        batch_op.drop_index("ix_opportunities_owner_status")

    op.drop_table("content_opportunities")
    op.drop_table("ai_skills")
    # ### end Alembic commands ###
